apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "main-pool"
spec:
  blocks:
  - start: "172.${subIp}.${index}.200"
    stop: "172.${subIp}.${index}.250"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-policy
spec:
  externalIPs: true
  loadBalancerIPs: true