apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        ports:
        - containerPort: 3000
          protocol: TCP
          name: server-tcp
        - name: server-udp
          containerPort: 5555
          protocol: UDP
          hostPort: 5555
        
---

apiVersion: v1
kind: Service
metadata:
  name: server-tcp
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
  - port: 3000
    targetPort: server-tcp
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: server-udp
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
  - port: 5555
    targetPort: server-udp
    protocol: UDP
